### ISSUE TITLE
could not parse max_hits_to_report as int64

### ISSUE THREAD

**Issue by bbimber** [BimberLab/nimble-aligner#76]
I am guessing this error is because the input nimble config omits this param, so it cant parse null into int? 

thread 'main' panicked at 'Error -- could not parse max_hits_to_report as int64', src/reference_library.rs:53:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Can either python or rust be made more tolerant to missing params (maybe default values)?

**Comment by hextraza** [comment]
fixed with https://github.com/BimberLab/nimble/commit/98a13abd81b9496a60d366c51d03a7b9f9bf7e90
